repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.77.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    # - id: terraform_checkov
    - id: terraform_tflint
      args:
          - '--args=--only=terraform_deprecated_interpolation'
          - '--args=--only=terraform_deprecated_index'
          - '--args=--only=terraform_unused_declarations'
          - '--args=--only=terraform_comment_syntax'
          - '--args=--only=terraform_documented_outputs'
          - '--args=--only=terraform_documented_variables'
          - '--args=--only=terraform_typed_variables'
          - '--args=--only=terraform_module_pinned_source'
          - '--args=--only=terraform_naming_convention'
          - '--args=--only=terraform_required_version'
          - '--args=--only=terraform_required_providers'
          - '--args=--only=terraform_standard_module_structure'
          - '--args=--only=terraform_workspace_remote'
    # - id: terraform_tfsec
    - id: terraform_validate
      args:
      - --hook-config=--retry-once-with-cleanup=true
    # - id: terrascan
    - id: terraform_docs
      args:
      - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
      - --hook-config=--add-to-existing-file=true     # Boolean. true or false
      - --hook-config=--create-file-if-not-exist=true

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
